- .gitignore
- description2html/description2html.py
- [ADD] Use of bs4 instead old BeautifulSoup 3.x. This let to manage in a
smart way the tags addition, elimination and wrapping.
- [ADD] Add a new attribute to the DescriptionToHtml class named
pretty_option. This option is False, but if set to True via code then
every title section from the rst file will be wrap into a section tag to
add the alternate change of color. Also manage the change or not of the h1
titles to use the css class from odoo.
- [IMP] Remove the maintainer section when creating the index.html if the
exist. Only show the footer.
- [ADD] head tag at the top of the html file is now created inside this code
using bs4. this way the header.html file in the data folder was deleted.
- [IMP] insert footer using bs4 at the end of the content of the html tag.
- [IMP] now the …
> [IMP] Multiple improvements to the description2html script.

- description2html/description2html.py
When generating a index.html using `description2html` script with tables inside the README.rst file will put the tables with ugly border
This PR set this table format to without border to make the index.html file more appealing
> [ADD] set the readme tables as tables without borders when generating the index.html file.

- pot_generator/README.md
- pot_generator/pot_generator.py
This script is going to be use in t2d generate docker and the reason to make this changes is to improve the time and get better the process of generate the pot files inside the container.
Right now this script need to be edited every time that is run. That because need to change the database, server name, port, user, password and module path to be use to extract the data. Adding this as parameters in the command line (parameters with set of defaults ready to use) will be easy to run the script.
Also, the script need to be updated to
> [IMP] update por_generator script to use argument command line

- odoo-instance/install
The odoo-instance scrpt depend on non standar argcomplete python package.
I will update the odoo-instance/install script to install the argcomplete
package there.
> [FIX] install odoo-instance: ImportError: No module named argcomplete

- odoo-instance/odoo-instance
this affect to odoo-instance restart subcommand.
> [IMP] odoo-instance: add wait after start postgres server to be sure that was start before create/delete databases

- odoo-i18n-export/install
When I execute the `odoo-i18n-export` command line it shows me this error:
```
$ odoo-i18n-export 
Traceback (most recent call last):
File "/root/tools/gist-vauxoo/odoo-i18n-export/odoo-i18n-export.py", line 9, in <module>
import oerplib
ImportError: No module named oerplib
```
Making `pip install oerplib` fix this problem, but maybe it should be a job to do in the `./install` script.
> No module named oerplib in odoo-i18n-export

- odoo-i18n-export/install
I recently installed the tool `odoo-i18n-export` but when I try to execute it, says that I have no permission to do it.
```
$ odoo-i18n-export 
-bash: /root/tools/gist-vauxoo/odoo-i18n-export/odoo-i18n-export.py: Permission denied
```
I fix it giving that script the execution bit
```
$ chmod +x odoo-i18n-export.py
```
But I think it should have execution permissions once the container is created.
> Permission denied trying to execute odoo-i18n-export

- odoo-instance/vauxoo.json
> NOTE: This is  temporal solution until we generate the json file using oca_dependecies of the main project and the dependencies projects
> odoo-instance: update repositories paths

- odoo-instance/vauxoo.json
odoo-afrs do not exist, odoo-afr it does.
> [FIX] odoo-instance: misspelling in repository name

- odoo-instance/odoo-instance
When use odoo-instance checkout command now we have an extra
parameter that is --checkout-comm PATH. This let us to pass a path to a
json file that is similar to the config json, but have a extra key per
branch_ commit key telling to odoo-instance in which commit should be
that branch. This command iterate on the branches and apply: git
checkout commit.
> [ADD] odoo-instance: new argument --checkout-commit PATH

- fix_product_category_all.py
Summary
-------------
With this script can be replaced 'All products' category that was supported until v6 by 'All' category from later versions.
_'All products'_ category from v6.1:
https://github.com/odoo/odoo/blob/6.1/addons/product/product_data.xml#L7
_'All'_ category from v7:
https://github.com/odoo/odoo/blob/7.0/addons/product/product_data.xml#L7
> [ADD] added script to replace older product category

- reset_admin_password.sql
How to run:
`psql -d DBNAME -a -f ~/tools/gist-vauxoo/reset_admin_password.sql`
After run:
http://my.odoo.server:port/web/reset_password?token=rsvabcdefghijykalklk&login=admin
- my.odoo.server = Odoo Server Domain
- port = Odoo Sever Port
- token = Static token (could be changed in script)
- login = Last login used for Administrator (admin by default)
> [ADD] new SQL script to reset admin pasword

- create_product_attributes.py
Summary
-------------
In script `create_product_attibutes.py` when an attribute is created the type by default will be set 'hidden'. But also will be check a mapper to assign a type specificlly.
> [REF] adapt script to include a attribute mapper

- create_product_attributes.py
Summary
-------------
Apparently when remove attribute is removed the variant now we need to add the default code to the new variant created.
> [FIX] create_product_attributes.py: fix missing default_code

- clean_vim
This script clean up swap and temporal files that do not let you open your
files in vim. Used when containers stop abruptly or anything happen that close
vim abruptly.
> [ADD] clean_vim: script to clean vim history

- stock_diagnosis/quants_differ_all_stock_moves.sql
- stock_diagnosis/quants_differ_logistic_qty.sql
- stock_diagnosis/quants_greater_in_stock_moves.sql
The following scripts are added:
- `quants_greater_in_stock_moves.sql`: detect differences between quants
and incoming stock moves
- `quants_differ_all_stock_moves.sql` detect differences between quants
and all stock moves (incoming and outgoing)
- `quants_differ_logistic_qty.sql`: detect differences between quants
and logistic quantities, when the module `stock_cost_segmentation` [1]
is installed
For more information, check the documentation on the mentioned scripts.
[1] https://github.com/Vauxoo/addons-vauxoo/tree/11.0/stock_cost_segmentation
> [ADD] stock_diagnosis: Scripts to detect discrepancies by quants and moves

- stock_diagnosis/quants_differ_all_stock_moves.sql
- stock_diagnosis/quants_greater_in_stock_moves.sql
The following fixes are applied:
- Take quantities from the stock move lines, instead of the stock moves
- Consider only moves in the 'Done' state
> [FIX] stock_diagnosis: Be more accurate when retrieving qtys from moves

- stock_diagnosis/quants_differ_logistic_qty.sql
All location types were being considered, which caused false positives.
> [FIX] stock_diagnosis: Consider only internal locations on logistic qtys

- res_config_settings_extract_fields.py
Server action to output all fields to be included on a
`res.config.settings` XML data, when initializing a module for an app of
an already-existing instance.
> [ADD] res_config_settings_extract_fields: Fields to init a module

- ir_module_module_extract_installed.py
This adds a server action to output all modules to be included on the
manifest, useful when initializing a module for an app of an
already-existing instance.
> [ADD] ir_module_module_extract_installed.py: Extract installed modules

- odoo-instance/odoo-instance
When modules are removed from the git repo, i.e. stop tracking changes from it, the directory may still exists after a `git pull` is done and this may cause non-expected behavior. So it is necessary to apply a `git clean` after the `git pull` have been taken place
> [IMP] odoo-instance: apply git clean after pulling new changes

- git-history-migrate-branch.sh
- git-shrinking-repo.sh
This PR provides a script that allows to migrate
modules from one project to another by:
- Taking Git history of module and creating a new branch in Destination Project.
- Creating a PR for history on Destination project
- Creating a new branch for getting rid of module on Source project.
- Creating a PR of module being got rid.
- Modifying oca_requirements.txt file on affected projects and adding new branches
of Source (without module) and Destination (with module) and Creating regarding PR.
> Git History Traslation between two Projects

- l10n_mx_edi_report_invoice.xml
Adding some information from SAT's format to printed CFDI
- Product code
- Unit code
- CFDI Usage
- Verify that both RFC (emitter and customer) are in printed CFDI,
even if they've changed.
Use:
PDF
> [IMP] l10n_mx_edi: add information in invoice report

- stock_diagnosis/quants_differ_all_stock_moves.sql
Sometimes there are very small differences that should not be considered
because, when rounded, they disappear.
> [FIX] stock_diagnosis: False positives due to rounding

- ir_module_module_extract_installed.py
The following changes are performed:
- Remove workaround implemented because `sorted` was not available in
server actions, but that's not the case anymore [1]
- Don't include `company_country`, because it's deprecated for recent
versions
- Ignore `base_automation`, we shouldn't encourage its installation, even
if it's already installed in production
- `web_dashboard` is automatically installed in newer versions, so it's
ignored
[1] https://github.com/odoo/odoo/pull/52208
> [REF] ir_module_module_extract_installed: Exclude more and rm workaround

- cloc_multiple_directories.py
If the directory exists but the database is not available, Cloc documentation does not provide a recursive way to get the number of line of code of every module inside a repository. This script solves that to get a table with each module inside a repository with just one line command and save that table in cloc_file.log.
> [ADD] cloc_multiple_directories: Count the line of code from a repository without the database.

- ir_module_module_extract_installed.py
l10n_mx_edi is marked as autoinstall, but it should be added anyway.
> [FIX] ir_module_module_extract_installed: don't exclude EDI modules

- generate_module_dependency_priority.py
Whenever a level is processed, it's popped , then modified and re-inserted. However, last level wasn't being re-inserted.
> [FIX] generate_module_dependency_priority: don't discard last level t#57540

- generate_module_dependency_priority.py
Consider more cases when excluding native modules:
- Author "Odoo" and "Odoo SA" (without dots)
- Some modules that have different authors but are actually of Odoo (e.g. sale_subscription)
> [IMP] generate_module_dependency_priority: better filter native modules t#57461

- gitlab_api.py
- gitlab_mr_template/ci_missing_tags-luisg/.gitlab-ci.yml
The following improvements are included:
- Create MR pushing from dev project whenever possible (e.g. vauxoo-dev)
- Include description also in commit, not only in MR
- Ensure source branch is deleted when the MR is merged, even if it's not the default behavior
- Allow to specify task ID for MR's title
- Make configurable whether version name will be prefixed to MR's title
- Don't prefix version name into resulting commit, only in MR
> [IMP] gitlab_api: several improvements t#58355

- gitlab_api.py
When creating an MR for a file contained into a sub-directory, if the directory doesn't exist yet, file creation fails.
> [FIX] gitlab_api: error when creating MR with sub-directories t#63281

- installed_custom_modules.py
Server action to output all installed modules that are not native, i.e. not maintained by Odoo S.A. This is usefuld to be used to fill the whitelist of modules to keep in post SQL migration scripts.
> [ADD] installed_custom_modules: extract installed non-native modules T#66890

- gitlab_api.py
To save time when calling pre-commit-vauxoo, just use the hook type "fix".
> [IMP] gitlab_api: only use fix in pre-commit-vauxoo T#61194

- assign_mx_uuid_to_moves.py
Moves comes with l10n_mx_edi_cfdi_uuid empty because there is no
filestore in the migration process, so it is required to apply this code as
a server action.
Co-authored-by: Luis Manuel <luis.manuel@vauxoo.com>
> [ADD] assign_mx_uuid_to_moves.py: Add server action to assign l10n_mx_edi_cfdi_uuid T#70525

- generate_module_dependency_priority.py
Several improvements are included to exclude native modules when generating custom ones, namely:
- Exclude CoA modules (named as l10n_XX), as they are generally not authored by Odoo, so they were not being considered as native ones.
- Make author comparison case insensitive, because modules like `l10n_co_edi` have "Odoo Sa" (lowercased "a") as author.
- Extend list of know native modules to include l10n latam modules and EDI localizations of Mexico and Peru.
> [IMP] generate_module_dependency_priority: improve excluded modules T#79128

- installed_custom_modules.py
Some modules like `html_editor` have "odoo" (lowercase) as author [1], so we need to consider authors on a case-insensitive manner.
[1]: https://github.com/odoo/odoo/pull/190655
> [IMP] installed_custom_modules: consider authors case insensitive T#86041

- ir_module_module_extract_installed.py
When extracting installed modules, test modules shouldn't be considered, even if they're installed in production.
> [FIX] ir_module_module_extract_installed: don't consider test modules T#89440

- installed_custom_modules.py
To determine whether a module is native, new criteria are added:
- Consider modules we know in advance are native but whose author in the manifest is not Odoo, e.g. l10n_mx_reports is authored by Vauxoo
- Consider other variations of "Odoo S.A." that are also used as module authors, e.g. "Odoo SA".
> [IMP] installed_custom_modules: new criteria to determine native modules T#86043
