vauxoo-dev/gist-vauxoo

DescriptionToReadmeMD.py

A new script to create readme.md files for modules is added, is used through a path into the object calling into the code by the moment

[ADD][DescriptionToReadmeMD.py] New script added to create README.md files for modules

---

md2rst.py

Task [vx#3889](https://www.vauxoo.com/web#id=3889&view_type=form&model=project.task&action=138)

[ADD] new script md2rst file that move all the md files for a given addons path to a rst files.

---

odoo-instance/odoo-instance
odoo-instance/yoytec.json

This script read a json file with the addons-path information of a instance and can:
- `--check`: list all the addons-paths status (to visually check that you are using the correct enviroment)
- `--update`: make a pull of all the addons-path to update the repositories related to the giveninstance 
TODO: there is need to change the local intances json config folder to run the script.

[NEW] odoo-instace script to update all the repos of a instance.

---

odoo-instance/odoo-instance

[IMP] improves odoo-instance script

---

odoo-instance/README.md
odoo-instance/forecast.json
odoo-instance/install
odoo-instance/odoo-instance
odoo-instance/yoytec.json

[ADD] modify odoo-instance script to make it easy to use inside a docker container generate via t2d

---

pot_generator/README.md
pot_generator/install
pot_generator/pot_generator.py

The original script is in:
http://bazaar.launchpad.net/~vauxoo/tools-openerp-vauxoo/trunk/view/head:/webservices/pot_generator.py

[ADD] migrate script to generate pot files.

---

odoo-instance/odoo-instance

Currently this is not happening, a python error occurs. But with this change
the error is fixed.

[IMP] odoo-instance: default vauxoo env will throw message if not exist

---

odoo-server/README.rst
odoo-server/createdb_depends
odoo-server/createdb_main
odoo-server/createdb_main_with_test
odoo-server/createdb_test
odoo-server/docker-t2d
odoo-server/odoo_server
odoo-server/reinstallmodule
odoo-server/run
odoo-server/test

This is a personal script ot @zaoral migrate to this repository in order to
improve the script and make it generic to be used inside t2d containers.

[ADD] odoo-server: new script that will let to manage data base easy via comamnd line.

---

res_groups_2_instances.py

`python res_groups_2_instances.py -d database_name -r user -w password  -D database_name -R user -W password`

[ADD]added script to compare all res.groups users beetwen 2 instances

---

res_groups_2_instances.py

[FIX] concatenated str and set object

[FIX] concatenated str and set object

---

odoo-server/docker-odoo-port

Add new script that will let to open the docker odoo instance in the
default web browser.

[ADD] docker-odoo-port script to open the odoo instance inside a container in the default browser.

---

odoo-profiling-results/full.py
odoo-profiling-results/small.py

original by @moylop260 
Add new scripts to re use when reading odoo profilling stats result file. this is a simple script that receive the name of the stat file and will filter the revelant information.

[ADD] odoo-profiling-results: new script to review stats files

---

odoo-instance/odoo-instance

Add new sub-command named summary that throw for every branch a summary indicationg status, diff, stash list, unmerged branches.

[IMP] odoo-instance: new sub command `summary`

---

odoo-instance/vauxoo.json

Odoo-apps repo also will be take into account when runing odoo-instance
subcommands.

[ADD] odoo-instance: update the json configuration to add the new repository added to the client instance.

---

odoo-instance/odoo-instance

This in order to indicate the user the changes that will be done in order to clean the current container instance. update the branches, python package and dependencies and re create the databases.

[IMP] odoo-instance: show the commands that will be run when use restart command

---

odoo-instance/odoo-instance

This is order to mantain the container small.

[IMP] odoo-instance: Do not fetch when do a restart

---

odoo-instance/vauxoo.json

Reverts vauxoo-dev/gist-vauxoo#68
Was a error from t2d fixed https://github.com/Vauxoo/travis2docker/pull/67

Revert "[ADD] odoo-instance: update path for build principal path."

---

reset_language

This script is useful for implementation time. TYP users are getting
some translation not updated in the instance. To avoid this, it's
necessary to deactivate, remove, and reload the system language. We
don't want to do it every time we update the in-production instance.
I had some +1 in https://github.com/Vauxoo/typ/pull/137
How to Run:
https://asciinema.org/a/cf4wcpw2xdha0uwxy0id6tgjc
Manual solution:
https://drive.google.com/file/d/0B0GA0dsW6w8GbXB3dUx1YVR4VkE/view?usp=sharing

[ADD] Script to reset the language

---

odoo-instance/odoo-instance

Add new command  named current_commit that show us the current commit information of each branch. This sub-command is equal to execute
```
git rev-parse HEAD
```
on each branch

[ADD] odoo-instance: new command current_commit

---

description2html/description2html.py

[ADD] Quick fix to be able to add html description to 10.0 modules

---

attribute_2_template.py
create_product_attributes.py

Summary:
--------------
Created a new script to convert product attributes in products, and assign it into a one of those fields: _Alternative Products_, _Accessory Products_ or _Optional Products._
Also:
- changed default values when create product attributes:
> In script `create_product_attibutes.py` when create a product attribute was included as default values: type 'Select' & not Create Variants.

[ADD] new script to convert attributes in products

---

create_product_attributes.py

Summary
-------------
In script `create_product_attibutes.py` before create a product will be loaded the product category using the name from a column of csv file.

[REF] changed script to load product category from name

---

create_product_attributes.py

Also:
* [FIX] wrong attribute type comparassion

[REF] support language in product categories

---

create_product_attributes.py

In create_product_attributes.py script

[REF] Change script to use website categ instead product categ

---

create_product_attributes.py

Summary
--------------
In script create_product_attributes.py after update or create products, all products that not in at the csv file will be inactivated to avoid inconsistency.

[REF] Inactive all products that not in on the csv file

---

create_product_attributes.py

Also:
- Remove blank spaces from product categories
- Display at end the quantity of products updates
& created.
- Change some field names.

[REF] Delete products that not in on the csv file

---

extract_odostudio_views.py

And to put them on XML files, groupped by model.

[ADD] extract_odostudio_views: Script to extract views created by Odoo Studio

---

stock_diagnosis/quants_differ_all_stock_moves.sql
stock_diagnosis/quants_differ_logistic_qty.sql

Now the company is taken into account, and product without incoming stock move lines are not excluded.

[IMP] quants_differ_all_stock_moves: Consider company & prods wo in sml

---

stock_diagnosis/moves_differ_quants.sql
stock_diagnosis/moves_wo_quants.sql
stock_diagnosis/quants_differ_all_stock_moves.sql
stock_diagnosis/sum_moves_negative.sql

- Retrieve missing quants for stock moves
- Retrieve moves whose resulting quantity is negative

[ADD] stock_diagnosis: New scripts

---

stock_diagnosis/moves_differ_quants.sql
stock_diagnosis/quants_differ_all_stock_moves.sql

- Take them into account in `quants_differ_all_stock_moves`
- Fix logic in `moves_differ_quants`

[FIX] stock_diagnosis: Consider lot, package & owner when comparing

---

stock_diagnosis/quants_differ_remaining_qty.sql

A new script is introduced to detect discrepancies between available
quantities (quants) and remaining quantities (stock moves).

[ADD] stock_diagnosis: Script for diffs between quants vs remaining qtys

---

upload_backup_upgrade.py

This adds a script to upload a database backup to odoo to be migrated,
via sftp.

[ADD] upload_db_to_upgrade: Upload DB to be migrated

---

github_miniapi.py

Three new methods are added:
- List all issues
- Close a pull request
- Close all pull requests

[IMP] github_miniapi: Implement list and close PRs

---

gitlab_api.py
gitlab_mr_template/variable_psql_version-luisg/variables.sh

To change PostgreSQL version from 14 → 15.
[IMP] gitlab_api: add param to cancel pipelines when creating MRs
In order to don't overload the runners.

[ADD] gitlab_api: template tofix PSQL version for Odoo v17.0 T#84059
